apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-sysalert
  namespace: pf9-monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['instance', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 10m
      receiver: 'webhook'
    receivers:
    - name: 'webhook'
