apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: pf9-monitoring
type: Opaque
stringData:
  datasources.yaml: |
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": false,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://sys-prometheus.pf9-monitoring.svc:9090",
                "version": 1
            }
        ]
    }
